USE freedomos;

CREATE TABLE IF NOT EXISTS notification_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  recipient VARCHAR(150) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  status VARCHAR(40) DEFAULT 'queued',
  meta JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
